# Generated by Django 5.2.5 on 2025-08-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_unidade_remove_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='estoque.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
