# Generated by Django 5.2.5 on 2025-08-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_produto_tipo', to='estoque.tipoproduto', verbose_name='Tipo de Produto'),
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_contato_cliente', to='estoque.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
