# Generated by Django 5.2.5 on 2025-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_tipo_produto_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='is_excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
    ]
